'use client';
import {useState} from 'react';
import {terranovaApi} from '../services/api';
const days=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'];
export default function EventDetail({promotion,schedule,configurations,onClose,onSaved}:{promotion:any;schedule:any;configurations:any[];onClose:()=>void;onSaved:()=>void}){
 const[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const[form,setForm]=useState({...promotion,dayOfWeek:schedule?.dayOfWeek||1,sendTime:schedule?.sendTime?.slice(0,5)||'09:00'});
 const config=configurations.find(c=>c.id===form.configurationId);
 const save=async()=>{setBusy(true);setError('');try{await terranovaApi.updatePromotion(promotion.id,{name:form.name,imageUrl:form.imageUrl,message:form.message,shift:form.shift,configurationId:+form.configurationId,active:form.active});if(schedule)await terranovaApi.updateSchedule(schedule.id,{dayOfWeek:+form.dayOfWeek,sendTime:form.sendTime,active:true});onSaved()}catch(e){setError(String(e))}finally{setBusy(false)}};
 return <div className="overlay detailOverlay"><section className="eventDetail"><button className="x" onClick={onClose}>×</button><div className="detailColor" style={{background:config?.color}}/><label>DETALLE DE PROMOCIÓN</label><h2>{editing?'Editar evento':form.name}</h2>{error&&<div className="loginError">{error}</div>}<div className="detailLayout"><div>{form.imageUrl&&<img src={form.imageUrl} alt={form.name}/>}<span className="pill" style={{background:config?.color}}>{config?.name}</span></div><div className="detailFields">{editing?<><label>Nombre<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>URL de imagen<input value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})}/></label><label>Mensaje<textarea value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></label><label>Configuración<select value={form.configurationId} onChange={e=>setForm({...form,configurationId:+e.target.value})}>{configurations.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><div className="row"><label>Turno<select value={form.shift} onChange={e=>setForm({...form,shift:e.target.value})}><option value="MORNING">Mañana</option><option value="AFTERNOON">Tarde</option></select></label><label>Día<select value={form.dayOfWeek} onChange={e=>setForm({...form,dayOfWeek:+e.target.value})}>{days.map((d,i)=><option value={i+1}>{d}</option>)}</select></label><label>Hora<input type="time" value={form.sendTime} onChange={e=>setForm({...form,sendTime:e.target.value})}/></label></div></>:<><p>{form.message}</p><dl><div><dt>Configuración</dt><dd>{config?.name}</dd></div><div><dt>Turno</dt><dd>{form.shift==='MORNING'?'Mañana':'Tarde'}</dd></div><div><dt>Programación</dt><dd>{days[form.dayOfWeek-1]} · {form.sendTime}</dd></div><div><dt>Estado</dt><dd>{form.active?'Activa':'Inactiva'}</dd></div></dl></>}</div></div><footer>{editing&&<button className="ghost" onClick={()=>setEditing(false)}>Cancelar</button>}<button className="primary" disabled={busy} onClick={editing?save:()=>setEditing(true)}>{busy?'⏳ Guardando…':editing?'Guardar cambios':'Editar información'}</button></footer></section></div>
}
