'use client';
import {useEffect,useState} from 'react';
import {terranovaApi} from '../services/api';
import LogTable from './Activity';
import EventDetail from './EventDetail';
import DayPicker from './DayPicker';
const days=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'];
type Config={id:number;name:string;url:string;apiKey:string;color:string;active:boolean};
type Promo={id:number;name:string;imageUrl:string;message:string;shift:string;active:boolean;configurationId:number};
type Schedule={id:number;promotionId:number;dayOfWeek:number;sendTime:string;active:boolean};
type Dashboard={promotions:Promo[];schedules:Schedule[];configurations:Config[];logs:any[]};
const blankPromo={name:'',imageUrl:'',message:'',shift:'MORNING',selectedDays:[1] as number[],sendTime:'09:00',configurationId:0,active:true};
const blankConfig={name:'',url:'http://localhost:3031/api/negocio_local/status/image',apiKey:'',color:'#D94F70'};
export default function Home(){
 const[auth,setAuth]=useState<boolean|null>(null),[credentials,setCredentials]=useState({email:'admin@terranova.pe',password:''}),[error,setError]=useState('');
 const[data,setData]=useState<Dashboard>({promotions:[],schedules:[],configurations:[],logs:[]}),[tab,setTab]=useState('agenda'),[promoOpen,setPromoOpen]=useState(false),[configOpen,setConfigOpen]=useState(false),[notice,setNotice]=useState(''),[selected,setSelected]=useState<{promotion:Promo;schedules:Schedule[];edit?:boolean}|null>(null),[adminName,setAdminName]=useState('Administrador');
 const[promo,setPromo]=useState(blankPromo),[config,setConfig]=useState(blankConfig),[busy,setBusy]=useState('');
 const load=async()=>{try{const d=await terranovaApi.dashboard();setData(d);setAuth(true);if(!promo.configurationId&&d.configurations[0])setPromo(x=>({...x,configurationId:d.configurations[0].id}))}catch{terranovaApi.logout();setAuth(false)}};
 useEffect(()=>{const user=terranovaApi.getUser();if(user?.name)setAdminName(user.name);terranovaApi.hasToken()?load():setAuth(false)},[]);
 const login=async(e:any)=>{e.preventDefault();try{const r=await terranovaApi.login(credentials.email,credentials.password);terranovaApi.setToken(r.accessToken);terranovaApi.setUser(r.user);setAdminName(r.user.name);await load()}catch{setError('Correo o contraseña incorrectos')}};
 const createPromo=async(e:any)=>{e.preventDefault();if(!promo.selectedDays.length){setNotice('Selecciona al menos un día');return}setBusy('create-promo');setNotice('Creando promoción y programando crons…');try{const p=await terranovaApi.createPromotion(promo);await terranovaApi.replaceSchedules(p.id,promo.selectedDays,promo.sendTime,promo.active);setPromoOpen(false);setPromo({...blankPromo,configurationId:data.configurations[0]?.id||0});setNotice(promo.active?`Promoción activa en ${promo.selectedDays.length} día(s)`:'Promoción registrada como inactiva');await load()}catch(e){setNotice(String(e))}finally{setBusy('')}};
 const createConfig=async(e:any)=>{e.preventDefault();setBusy('create-config');setNotice('Guardando configuración…');try{const c=await terranovaApi.createConfiguration(config);setConfigOpen(false);setConfig(blankConfig);setNotice('Configuración creada');await load();setPromo(x=>({...x,configurationId:c.id}))}catch(e){setNotice(String(e))}finally{setBusy('')}};
 const send=async(id:number)=>{setBusy(`send-${id}`);setNotice('Envío en proceso…');try{await terranovaApi.sendPromotion(id);setNotice('Promoción enviada correctamente');await load()}catch(e){setNotice(`Error al enviar: ${String(e)}`)}finally{setBusy('')}};
 const removePromo=async(id:number)=>{if(!confirm('¿Eliminar promoción?'))return;setBusy(`delete-${id}`);try{await terranovaApi.deletePromotion(id);setNotice('Promoción eliminada');await load()}catch(e){setNotice(String(e))}finally{setBusy('')}};
 const duplicatePromo=async(id:number)=>{setBusy(`duplicate-${id}`);setNotice('Duplicando promoción…');try{const result=await terranovaApi.duplicatePromotion(id);await load();setNotice('Copia creada como borrador. Edita sus datos y selecciona Activa cuando esté lista.');setSelected({promotion:result.promotion,schedules:result.schedules,edit:true})}catch(e){setNotice(String(e))}finally{setBusy('')}};
 const togglePromo=async(p:Promo)=>{setBusy(`status-${p.id}`);try{await terranovaApi.setPromotionStatus(p.id,!p.active);setNotice(!p.active?'Promoción activada: cron y envío habilitados':'Promoción inactivada: cron y envío bloqueados');await load()}catch(e){setNotice(String(e))}finally{setBusy('')}};
 const cfg=(id:number)=>data.configurations.find(c=>c.id===id);
 if(auth===null)return <div className="loginPage"><div className="spinner">TN</div></div>;
 if(!auth)return <div className="loginPage"><form className="loginBox" onSubmit={login}><div className="loginBrand">TN</div><label>ACCESO ADMINISTRATIVO</label><h1>Bienvenido a Terranova</h1><p>Ingresa para gestionar promociones.</p>{error&&<div className="loginError">{error}</div>}<span>Correo</span><input type="email" value={credentials.email} onChange={e=>setCredentials({...credentials,email:e.target.value})}/><span>Contraseña</span><input type="password" value={credentials.password} onChange={e=>setCredentials({...credentials,password:e.target.value})}/><button className="primary">Ingresar</button></form></div>;
 return <div className="app"><aside><h2><i>TN</i> Terranova<small>Gestor de promociones</small></h2>{[['agenda','▦ Resumen'],['promos','◉ Promociones'],['config','⚙ Configuraciones']].map(x=><button key={x[0]} className={tab===x[0]?'on':''} onClick={()=>setTab(x[0])}>{x[1]}</button>)}<footer>● Automatización activa<small>Worker revisa cada minuto</small><button onClick={()=>{terranovaApi.logout();setAuth(false)}}>Cerrar sesión</button></footer></aside><main>
 {selected&&<EventDetail promotion={selected.promotion} schedules={selected.schedules} configurations={data.configurations} startEditing={selected.edit} onClose={()=>setSelected(null)} onSaved={async()=>{setSelected(null);setNotice('Información actualizada');await load()}}/>}<header><div><label>ADMINISTRACIÓN</label><h1>{tab==='agenda'?`Hola, ${adminName}`:tab==='promos'?'Promociones':'Cuentas WAHA'}</h1><p>{tab==='config'?'Administra los destinos de envío.':'Organiza y programa tus estados de WhatsApp.'}</p></div><button className="primary" onClick={()=>tab==='config'?setConfigOpen(true):setPromoOpen(true)}>＋ {tab==='config'?'Nueva configuración':'Nueva promoción'}</button></header>{notice&&<div className="notice">{notice}</div>}
 {tab==='agenda'&&<><section className="stats"><b>📣 <span>{data.promotions.filter(p=>p.active).length}<small>Promociones activas</small></span></b><b>▣ <span>{data.configurations.length}<small>Configuraciones</small></span></b><b>✓ <span>{data.logs.filter(x=>x.status==='SENT').length}<small>Envíos exitosos</small></span></b></section><div className="legend">{data.configurations.map(c=><span key={c.id}><i style={{background:c.color}}/> {c.name}</span>)}</div><section className="panel"><h2>Semana de promociones</h2><p>Una promoción puede aparecer en varios días. Haz clic para ver o editar.</p><div className="week">{days.map((d,i)=><div className="day" key={d}><b>{d}</b>{data.schedules.filter(s=>s.dayOfWeek===i+1&&s.active).map(s=>{const p=data.promotions.find(p=>p.id===s.promotionId),c=p&&cfg(p.configurationId);return p?.active&&<article key={s.id} onClick={()=>setSelected({promotion:p,schedules:data.schedules.filter(x=>x.promotionId===p.id)})} style={{borderLeftColor:c?.color,background:`${c?.color||'#ddd'}18`}}><strong>{p.name}</strong><em style={{color:c?.color}}>{c?.name}</em><small>◷ {s.sendTime.slice(0,5)} · {p.shift==='MORNING'?'Mañana':'Tarde'}</small></article>})}</div>)}</div></section></>}
 {tab==='promos'&&<><section className="panel cards">{data.promotions.map(p=>{const c=cfg(p.configurationId);return <article className={`card ${p.active?'':'isInactive'}`} key={p.id} style={{borderTop:`5px solid ${c?.color}`}}><div className="configBadge" style={{background:c?.color}}>{c?.name}</div><button className={`statusToggle ${p.active?'active':'inactive'}`} disabled={!!busy} onClick={()=>togglePromo(p)}>{busy===`status-${p.id}`?'Actualizando…':p.active?'● Activa':'○ Inactiva'}</button><img src={p.imageUrl}/><h3>{p.name}</h3><p>{p.message}</p><button disabled={!!busy||!p.active} onClick={()=>send(p.id)}>{busy===`send-${p.id}`?'⏳ Enviando…':p.active?'Enviar ahora':'Envío bloqueado'}</button><button className="duplicateBtn" disabled={!!busy} onClick={()=>duplicatePromo(p.id)}>{busy===`duplicate-${p.id}`?'Duplicando…':'Duplicar'}</button><button className="editBtn" onClick={()=>setSelected({promotion:p,schedules:data.schedules.filter(s=>s.promotionId===p.id)})}>Ver / Editar</button><button className="del" disabled={!!busy} onClick={()=>removePromo(p.id)}>{busy===`delete-${p.id}`?'Eliminando…':'Eliminar'}</button></article>})}</section><section className="panel activityPanel"><h2>Historial de envíos</h2><LogTable data={data}/></section></>}
 {tab==='config'&&<section className="configCards">{data.configurations.map(c=><article className="configCard" key={c.id}><div className="colorBar" style={{background:c.color}}/><h2>{c.name}</h2><span className="pill" style={{background:c.color}}>● Activa</span><p>{c.url}</p><small>{data.promotions.filter(p=>p.configurationId===c.id).length} promociones asociadas</small><button className="del" onClick={()=>confirm('¿Eliminar configuración sin promociones?')&&terranovaApi.deleteConfiguration(c.id).then(load).catch(e=>setNotice(String(e)))}>Eliminar</button></article>)}</section>}
 </main>
 {promoOpen&&<div className="overlay"><form className="modal" onSubmit={createPromo}><button type="button" className="x" onClick={()=>setPromoOpen(false)}>×</button><label>NUEVO CONTENIDO</label><h2>Crear promoción</h2><select className="wide" value={promo.configurationId} onChange={e=>setPromo({...promo,configurationId:+e.target.value})} required><option value="">Selecciona la configuración WAHA</option>{data.configurations.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><input placeholder="Nombre" value={promo.name} onChange={e=>setPromo({...promo,name:e.target.value})} required/><input type="url" placeholder="URL imagen" value={promo.imageUrl} onChange={e=>setPromo({...promo,imageUrl:e.target.value})} required/>{promo.imageUrl&&<img src={promo.imageUrl}/>}<textarea placeholder="Texto a enviar" value={promo.message} onChange={e=>setPromo({...promo,message:e.target.value})} required/><select value={promo.shift} onChange={e=>setPromo({...promo,shift:e.target.value})}><option value="MORNING">Turno mañana</option><option value="AFTERNOON">Turno tarde</option></select><input type="time" value={promo.sendTime} onChange={e=>setPromo({...promo,sendTime:e.target.value})}/><DayPicker value={promo.selectedDays} onChange={selectedDays=>setPromo({...promo,selectedDays})}/><label className="statusField">Estado<select value={promo.active?'active':'inactive'} onChange={e=>setPromo({...promo,active:e.target.value==='active'})}><option value="active">Activa — habilita envío y cron</option><option value="inactive">Inactiva — no se enviará</option></select></label><button className="primary" disabled={!promo.selectedDays.length}>Crear y programar</button></form></div>}
 {configOpen&&<div className="overlay"><form className="modal configModal" onSubmit={createConfig}><button type="button" className="x" onClick={()=>setConfigOpen(false)}>×</button><label>NUEVA CUENTA WAHA</label><h2>Crear configuración</h2><input placeholder="Nombre, ej. Terranova Restobar" value={config.name} onChange={e=>setConfig({...config,name:e.target.value})} required/><input type="color" title="Color identificador" value={config.color} onChange={e=>setConfig({...config,color:e.target.value})}/><input className="wide" type="url" placeholder="URL endpoint" value={config.url} onChange={e=>setConfig({...config,url:e.target.value})} required/><input className="wide" type="password" placeholder="X-Api-Key" value={config.apiKey} onChange={e=>setConfig({...config,apiKey:e.target.value})} required/><button className="primary">Guardar configuración</button></form></div>}
 </div>
}
