'use client';
import {useEffect,useMemo,useState} from 'react';
import {terranovaApi} from '../services/api';

type Config={id:number;name:string;color:string;active:boolean};
type Group={id:number;configurationId:number;session:string;groupChatId:string;name:string;active:boolean;lastSyncedAt?:string};
type Participant={id:number;groupId:number;wahaParticipantId:string;phone?:string;alias?:string;role:string;active:boolean;allowReminders:boolean};
type Reminder={id:number;groupId:number;participantId:number;subject:string;message:string;selectedDays?:number[];sendTime?:string;scheduledAt:string;status:string;active:boolean;sentAt?:string;lastError?:string;createdAt:string;updatedAt:string};
type Overview={groups:Group[];participants:Participant[];reminders:Reminder[];deliveries:any[]};
const empty:Overview={groups:[],participants:[],reminders:[],deliveries:[]};
const statusName=(x:string)=>({SCHEDULED:'Programado',PROCESSING:'Procesando',SENT:'Enviado',FAILED:'Falló',CANCELLED:'Cancelado'}[x]||x);
const weekDays=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'];

function ParticipantRow({item,onSaved}:{item:Participant;onSaved:()=>void}){
 const[alias,setAlias]=useState(item.alias||''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false),[error,setError]=useState('');
 useEffect(()=>setAlias(item.alias||''),[item.alias]);
 const save=async()=>{setBusy(true);setSaved(false);setError('');try{await terranovaApi.updateGroupParticipant(item.id,{alias});await onSaved();setSaved(true)}catch(e){setError(String(e))}finally{setBusy(false)}};
 return <tr><td><b>{item.alias||'Sin alias'}</b><small>{item.wahaParticipantId}</small></td><td>{item.role}</td><td><input value={alias} placeholder="Ej. Juan Pérez" onChange={e=>{setAlias(e.target.value);setSaved(false)}}/>{error&&<small className="aliasError">No se pudo guardar</small>}</td><td><button className="mini" disabled={busy||alias.trim()===(item.alias||'')} onClick={save}>{busy?'Guardando…':saved?'✓ Guardado':'Guardar alias'}</button></td></tr>
}

export default function ReminderModule({configurations}:{configurations:Config[]}){
 const[data,setData]=useState<Overview>(empty),[view,setView]=useState('groups'),[selectedGroup,setSelectedGroup]=useState<number|''>(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(''),[agendaPage,setAgendaPage]=useState(1);
 const[groupForm,setGroupForm]=useState({configurationId:configurations[0]?.id||0,session:'negocio_local',groupChatId:'',name:''});
 const[reminderForm,setReminderForm]=useState({groupId:0,participantId:0,subject:'',message:'',selectedDays:[1] as number[],sendTime:'09:00'});
 const load=async()=>{const value=await terranovaApi.reminderOverview();setData(value);if(!selectedGroup&&value.groups[0])setSelectedGroup(value.groups[0].id)};
 useEffect(()=>{load().catch(e=>setNotice(String(e)))},[]);
 useEffect(()=>{if(!groupForm.configurationId&&configurations[0])setGroupForm(x=>({...x,configurationId:configurations[0].id}))},[configurations]);
 const participants=useMemo(()=>data.participants.filter(p=>p.groupId===Number(selectedGroup)),[data.participants,selectedGroup]);
 const remindersPerPage=8,orderedReminders=useMemo(()=>[...data.reminders].sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime()),[data.reminders]);
 const agendaPages=Math.max(1,Math.ceil(orderedReminders.length/remindersPerPage)),visibleReminders=orderedReminders.slice((agendaPage-1)*remindersPerPage,agendaPage*remindersPerPage);
 useEffect(()=>{if(agendaPage>agendaPages)setAgendaPage(agendaPages)},[agendaPage,agendaPages]);
 const activeParticipants=data.participants.filter(p=>p.groupId===reminderForm.groupId&&p.active&&p.allowReminders);
 const createGroup=async(e:any)=>{e.preventDefault();setBusy('group');setNotice('');try{const g=await terranovaApi.createReminderGroup(groupForm);await load();setSelectedGroup(g.id);setGroupForm(x=>({...x,groupChatId:'',name:''}));setNotice('Grupo registrado. Ahora sincroniza sus participantes.')}catch(e){setNotice(String(e))}finally{setBusy('')}};
 const sync=async(id:number)=>{setBusy(`sync-${id}`);setNotice('Consultando participantes en WAHA…');try{const r=await terranovaApi.syncReminderGroup(id);await load();setSelectedGroup(id);setNotice(`${r.synced} participantes sincronizados`)}catch(e){setNotice(String(e))}finally{setBusy('')}};
 const createReminder=async(e:any)=>{e.preventDefault();if(!reminderForm.selectedDays.length){setNotice('Selecciona al menos un día');return}setBusy('reminder');setNotice('');try{await terranovaApi.createReminder({...reminderForm,deliveryMode:'GROUP_MENTION',timezone:'America/Lima'});await load();setReminderForm(x=>({...x,subject:'',message:''}));setNotice('Recordatorio semanal programado correctamente');setView('agenda')}catch(e){setNotice(String(e))}finally{setBusy('')}};
 const cancel=async(id:number)=>{if(!confirm('¿Cancelar este recordatorio?'))return;await terranovaApi.cancelReminder(id);await load()};
 const sendNow=async(id:number)=>{if(!confirm('¿Enviar este recordatorio ahora al grupo?'))return;setBusy(`send-${id}`);try{await terranovaApi.sendReminderNow(id);setNotice('Recordatorio enviado');await load()}catch(e){setNotice(String(e));await load()}finally{setBusy('')}};
 const group=(id:number)=>data.groups.find(g=>g.id===id),participant=(id:number)=>data.participants.find(p=>p.id===id);
 return <div className="reminderModule">
  <nav className="reminderTabs">{[['groups','Grupos'],['participants','Participantes'],['new','Nuevo recordatorio'],['agenda','Agenda e historial']].map(x=><button key={x[0]} className={view===x[0]?'active':''} onClick={()=>setView(x[0])}>{x[1]}</button>)}</nav>
  {notice&&<div className="moduleNotice">{notice}</div>}
  {view==='groups'&&<div className="reminderColumns"><form className="reminderPanel" onSubmit={createGroup}><label>NUEVO GRUPO</label><h2>Registrar grupo de WhatsApp</h2><span>Cuenta WAHA</span><select value={groupForm.configurationId} onChange={e=>setGroupForm({...groupForm,configurationId:Number(e.target.value)})} required><option value="">Seleccionar</option>{configurations.filter(c=>c.active).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><span>Nombre interno</span><input placeholder="Ej. Equipo de ventas" value={groupForm.name} onChange={e=>setGroupForm({...groupForm,name:e.target.value})} required/><span>Sesión WAHA</span><input value={groupForm.session} onChange={e=>setGroupForm({...groupForm,session:e.target.value})} required/><span>Chat ID del grupo</span><input placeholder="120363...@g.us" value={groupForm.groupChatId} onChange={e=>setGroupForm({...groupForm,groupChatId:e.target.value})} required/><button className="primary" disabled={busy==='group'}>{busy==='group'?'Guardando…':'Registrar grupo'}</button></form><section className="reminderPanel"><label>GRUPOS REGISTRADOS</label><h2>{data.groups.length} grupos</h2><div className="groupList">{!data.groups.length&&<p>Aún no hay grupos registrados.</p>}{data.groups.map(g=><article key={g.id} className={!g.active?'muted':''}><div><b>{g.name}</b><small>{g.session} · {g.groupChatId}</small><small>{g.lastSyncedAt?`Sincronizado ${new Date(g.lastSyncedAt).toLocaleString('es-PE')}`:'Pendiente de sincronizar'}</small></div><button disabled={!!busy||!g.active} onClick={()=>sync(g.id)}>{busy===`sync-${g.id}`?'Sincronizando…':'Sincronizar'}</button></article>)}</div></section></div>}
  {view==='participants'&&<section className="reminderPanel"><div className="panelHeading"><div><label>DIRECTORIO</label><h2>Participantes y alias</h2></div><select value={selectedGroup} onChange={e=>setSelectedGroup(Number(e.target.value))}><option value="">Selecciona un grupo</option>{data.groups.map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select></div>{selectedGroup&&<button className="syncTop" disabled={!!busy} onClick={()=>sync(Number(selectedGroup))}>↻ Actualizar desde WAHA</button>}<div className="tableWrap"><table><thead><tr><th>Participante</th><th>Rol</th><th>Alias interno</th><th></th></tr></thead><tbody>{participants.map(p=><ParticipantRow item={p} key={p.id} onSaved={load}/>)}</tbody></table></div>{selectedGroup&&!participants.length&&<p>No hay participantes. Sincroniza el grupo para obtenerlos desde WAHA.</p>}</section>}
  {view==='new'&&<form className="reminderPanel reminderForm" onSubmit={createReminder}><label>PROGRAMACIÓN SEMANAL</label><h2>Nuevo recordatorio con mención</h2><p>El mensaje se publicará dentro del grupo, mencionará al participante y se repetirá cada semana en los días marcados.</p><span>Grupo</span><select value={reminderForm.groupId} onChange={e=>setReminderForm({...reminderForm,groupId:Number(e.target.value),participantId:0})} required><option value="">Seleccionar grupo</option>{data.groups.filter(g=>g.active).map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select><span>Participante</span><select value={reminderForm.participantId} onChange={e=>setReminderForm({...reminderForm,participantId:Number(e.target.value)})} required><option value="">Seleccionar participante</option>{activeParticipants.map(p=><option value={p.id} key={p.id}>{p.alias||'Sin alias'} — {p.wahaParticipantId}</option>)}</select><span>Asunto</span><input placeholder="Ej. Entrega de documentación" value={reminderForm.subject} onChange={e=>setReminderForm({...reminderForm,subject:e.target.value})} required/><span>Días de envío</span><div className="reminderDays">{weekDays.map((day,index)=>{const value=index+1,selected=reminderForm.selectedDays.includes(value);return <label className={selected?'selected':''} key={day}><input type="checkbox" checked={selected} onChange={()=>setReminderForm({...reminderForm,selectedDays:selected?reminderForm.selectedDays.filter(x=>x!==value):[...reminderForm.selectedDays,value].sort()})}/><span>{day.slice(0,3)}</span></label>})}</div><span>Hora de envío</span><input type="time" value={reminderForm.sendTime} onChange={e=>setReminderForm({...reminderForm,sendTime:e.target.value})} required/><span>Mensaje</span><textarea placeholder="Ej. recuerda presentar tu documentación. Puedes usar {{alias}}." value={reminderForm.message} onChange={e=>setReminderForm({...reminderForm,message:e.target.value})} required/><small>Se agregará automáticamente la mención real de WhatsApp. Usa {'{{alias}}'} para insertar el alias interno.</small><button className="primary" disabled={busy==='reminder'||!reminderForm.selectedDays.length}>{busy==='reminder'?'Programando…':'Programar recordatorio semanal'}</button></form>}
  {view==='agenda'&&<section className="reminderPanel"><label>CONTROL DE ENVÍOS</label><div className="agendaHeading"><h2>Agenda e historial</h2><small>{orderedReminders.length} recordatorios · Más recientes primero</small></div><div className="reminderList">{!orderedReminders.length&&<p>No hay recordatorios.</p>}{visibleReminders.map(r=><article key={r.id}><div className={`reminderStatus ${r.status.toLowerCase()}`}>{statusName(r.status)}</div><div><b>{r.subject||'Recordatorio'}</b><strong>{participant(r.participantId)?.alias||participant(r.participantId)?.wahaParticipantId||'Participante'}</strong><small>{group(r.groupId)?.name} · Próximo envío: {new Date(r.scheduledAt).toLocaleString('es-PE')}</small>{r.selectedDays?.length&&<small>{r.selectedDays.map(d=>weekDays[d-1]).join(', ')} a las {r.sendTime?.slice(0,5)}</small>}<p>{r.message}</p>{r.lastError&&<em>{r.lastError}</em>}</div><div className="reminderActions">{['SCHEDULED','FAILED'].includes(r.status)&&<button disabled={!!busy} onClick={()=>sendNow(r.id)}>{busy===`send-${r.id}`?'Enviando…':'Enviar ahora'}</button>}{r.status==='SCHEDULED'&&<button className="cancel" onClick={()=>cancel(r.id)}>Cancelar</button>}</div></article>)}</div>{orderedReminders.length>0&&<nav className="pagination"><button disabled={agendaPage===1} onClick={()=>setAgendaPage(x=>x-1)}>← Anterior</button><span>Página {agendaPage} de {agendaPages}</span><button disabled={agendaPage===agendaPages} onClick={()=>setAgendaPage(x=>x+1)}>Siguiente →</button></nav>}</section>}
 </div>
}
